name = "AutoEncoderToolkit"
uuid = "1575904b-3569-468b-ae7a-8569c4d6dae9"
authors = ["Manuel Razo-Mejia"]
version = "0.0.3"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TaylorDiff = "b36ab563-344f-407b-a36a-4f200bebf99c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"

[extensions]
AutoEncoderToolkitCUDAExt = "CUDA"

[compat]
CUDA = "^5.3.3"
ChainRulesCore = "^1.23.0"
Clustering = "^0.15.7"
Distances = "^0.10.11"
Distributions = "^0.25.108"
EllipsisNotation = "^1.8.0"
Flux = "^0.14.15"
ForwardDiff = "^0.10.36"
NearestNeighbors = "^0.4.16"
StatsBase = "^0.34.3"
TaylorDiff = "^0.2.1"
Zygote = "^0.6.69"
cuDNN = "^1.3.1"
julia = "^1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
